language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - npm install -g serverless
  - yarn deploy
env:
  global:
  - secure: FKPvLKi8o988OcuJ+JlsJTmTs9ZRwr9sYz/BMemIt/QWh8pfpuYmjZt075qb4np5WMIevKOy0Ct5iRejogIOJ4U3dv2gqUO4rhLH0pbfAX//DVzT/eal5IZD/f4AjLwM8kFJFSdTZwse3zcSBuzhElFnrQP7/abhj8971qlRmJbOu1kfv0Tc4nG1EfPwXPy5wGfnuNlHxOMMLmPS/JAZh6FRn9h3jz7oFG1xgqh5/CZLHOi0Fd/s0rniTxT4TKCrhkooQ8agOQeUmJKzs3Gg7elLwt5CvRmfQsg5iDkxZ4bnykHeUYvTBN6tuV4BH5b5sQSIrmXSbrQtzJlxamz5N2KiHQkXgtbGMDoluZXGlzgB5VZgI4FRuileRrW2JD3/74HzG1hFF6V3tpFAaJyVQVUq0qZ50fBjlG7fUNP2wqHJiZR9/apLTCUBqBfC82lH7AU3vX6r0gJXp9hyQGXULa/D8qGL3GxmHqewmD5OtM9l5StEXHIalnNvVs/e5Gbgn8JPCkNMaa79a1stBUhuX3BAOeE1aHM6Kr04W+nxtcGn/xM6eZu3hhpRSbEZios6IYyTCfD9nz/58i9zukR4YEXvauUcCaPbks6SoDvLDBKuz/Tvd9SuRWMXc1Lrqe83ofeRUQheCwDWI3zoe+ZuiAa1AbfP6IYY+Mb2v7vg57w=
  - secure: TgAcnv/mKBnXHdTnEDy44JY6nlJNh1NMq2IPPhmKYtIItr8f1QQNrkko9w/jCKxJ2ek1CN7Ch4uM2Nr38NOiZFDw4gAwLeVER2F+lI/Lxm0Uam4TFbKwAHCEljkhx/XQ8zRfCFl+2DFhrSDAk1bmTIT8bIFDveku65h7OyGFqGdePzXqZeTcu037Juz0NOqPZ4nBU1YGoUjrLnbyvX44TTSGZvRKcml+jDGFFyaCh9X5mWu6VHCrduGBeXe2wq02ecPb/fi4u+wwCy2+XHSgq+4QHJQDgYujbkjRYEd6rjshbQMobd1lCK5vEchoH7Bodm2NASqZKmHMaGTfjlultkI4N9q9BsBSTRrvYflcD04l0weACWkLNbg4TiLcONNCwaIMWdM0AErnmowx3jauT4vtWCpPbslwQs6ADyCsmkMxiyBSUl+w+2LMnf+bqRyGOPC3egk31pv3fR4T8uuontJeuhWkikx7otPW0+j+RzxHRsTJ5QrMLl3JZayBl31t0EKFsGoKXCsln8K3o6DEtrgaUO+bbN/ATvXLo1ufn2Hn2qgsoWsDKpxNzx0aeojIPXSilK+9Kngafc28WCz0f8GwzRDyCfqHHFnI5uwRU4uQk68wZ4XcC6xyQ6FATwDOFR9fyCUO6G3ME8Ee94SZmJHLE3ETQhFTM7gfD8l/nqM=
